% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={AMS 580 Final Exam},
  pdfauthor={Kachun Huang},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{AMS 580 Final Exam}
\author{Kachun Huang}
\date{2025-05-14}

\begin{document}
\maketitle

\section{\texorpdfstring{AMS 580 Final Exam \textbf{Seat Number
C5}}{AMS 580 Final Exam Seat Number C5}}\label{ams-580-final-exam-seat-number-c5}

\section{Task 1}\label{task-1}

\subsection{Import Library}\label{import-library}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(randomForest)}
\FunctionTok{library}\NormalTok{(xgboost)}
\FunctionTok{library}\NormalTok{(Matrix)}
\FunctionTok{library}\NormalTok{(keras)}
\FunctionTok{library}\NormalTok{(tensorflow)}
\FunctionTok{library}\NormalTok{(reticulate)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(tidyquant)}
\FunctionTok{library}\NormalTok{(zoo)}
\FunctionTok{library}\NormalTok{(magrittr)}
\end{Highlighting}
\end{Shaded}

\subsection{Import Data}\label{import-data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data1 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"/Users/thomashuang/Downloads/data\_1.csv"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Age Gender Occupation Sleep.Hours Physical.Activity..hrs.week.
## 1  29 Female     Artist         6.0                          2.7
## 2  46  Other      Nurse         6.2                          5.7
## 3  64   Male      Other         5.0                          3.7
## 4  20 Female  Scientist         5.8                          2.8
## 5  49 Female      Other         8.2                          2.3
## 6  53   Male      Other         6.4                          6.5
##   Caffeine.Intake..mg.day. Alcohol.Consumption..drinks.week. Smoking
## 1                      181                                10     Yes
## 2                      200                                 8     Yes
## 3                      117                                 4      No
## 4                      360                                 6     Yes
## 5                      247                                 4     Yes
## 6                      235                                 2      No
##   Family.History.of.Anxiety Stress.Level..1.10. Heart.Rate..bpm.
## 1                        No                  10              114
## 2                       Yes                   1               62
## 3                       Yes                   1               91
## 4                        No                   4               86
## 5                        No                   1               98
## 6                        No                   9               84
##   Breathing.Rate..breaths.min. Sweating.Level..1.5. Dizziness Medication
## 1                           14                    4        No        Yes
## 2                           23                    2       Yes         No
## 3                           28                    3        No         No
## 4                           17                    3        No         No
## 5                           19                    4       Yes        Yes
## 6                           14                    3        No        Yes
##   Therapy.Sessions..per.month. Recent.Major.Life.Event Diet.Quality..1.10.
## 1                            3                     Yes                   7
## 2                            2                      No                   8
## 3                            1                     Yes                   1
## 4                            0                      No                   1
## 5                            1                      No                   3
## 6                            2                     Yes                   5
##   Anxiety.Level..1.10.
## 1                    5
## 2                    3
## 3                    1
## 4                    2
## 5                    1
## 6                    4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1100 obs. of  19 variables:
##  $ Age                              : int  29 46 64 20 49 53 20 54 51 59 ...
##  $ Gender                           : chr  "Female" "Other" "Male" "Female" ...
##  $ Occupation                       : chr  "Artist" "Nurse" "Other" "Scientist" ...
##  $ Sleep.Hours                      : num  6 6.2 5 5.8 8.2 6.4 7.9 6.3 6.6 5.1 ...
##  $ Physical.Activity..hrs.week.     : num  2.7 5.7 3.7 2.8 2.3 6.5 2.5 5.5 3.1 4.8 ...
##  $ Caffeine.Intake..mg.day.         : int  181 200 117 360 247 235 78 535 587 159 ...
##  $ Alcohol.Consumption..drinks.week.: int  10 8 4 6 4 2 14 15 2 15 ...
##  $ Smoking                          : chr  "Yes" "Yes" "No" "Yes" ...
##  $ Family.History.of.Anxiety        : chr  "No" "Yes" "Yes" "No" ...
##  $ Stress.Level..1.10.              : int  10 1 1 4 1 9 8 5 2 5 ...
##  $ Heart.Rate..bpm.                 : int  114 62 91 86 98 84 118 113 81 95 ...
##  $ Breathing.Rate..breaths.min.     : int  14 23 28 17 19 14 21 19 22 28 ...
##  $ Sweating.Level..1.5.             : int  4 2 3 3 4 3 5 1 1 5 ...
##  $ Dizziness                        : chr  "No" "Yes" "No" "No" ...
##  $ Medication                       : chr  "Yes" "No" "No" "No" ...
##  $ Therapy.Sessions..per.month.     : int  3 2 1 0 1 2 1 0 2 1 ...
##  $ Recent.Major.Life.Event          : chr  "Yes" "No" "Yes" "No" ...
##  $ Diet.Quality..1.10.              : int  7 8 1 1 3 5 2 7 8 1 ...
##  $ Anxiety.Level..1.10.             : int  5 3 1 2 1 4 4 4 3 4 ...
\end{verbatim}

\subsection{Data Cleaning}\label{data-cleaning}

\subsubsection{Remove Missing rows}\label{remove-missing-rows}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data1 }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(data1)}
\FunctionTok{str}\NormalTok{(data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1100 obs. of  19 variables:
##  $ Age                              : int  29 46 64 20 49 53 20 54 51 59 ...
##  $ Gender                           : chr  "Female" "Other" "Male" "Female" ...
##  $ Occupation                       : chr  "Artist" "Nurse" "Other" "Scientist" ...
##  $ Sleep.Hours                      : num  6 6.2 5 5.8 8.2 6.4 7.9 6.3 6.6 5.1 ...
##  $ Physical.Activity..hrs.week.     : num  2.7 5.7 3.7 2.8 2.3 6.5 2.5 5.5 3.1 4.8 ...
##  $ Caffeine.Intake..mg.day.         : int  181 200 117 360 247 235 78 535 587 159 ...
##  $ Alcohol.Consumption..drinks.week.: int  10 8 4 6 4 2 14 15 2 15 ...
##  $ Smoking                          : chr  "Yes" "Yes" "No" "Yes" ...
##  $ Family.History.of.Anxiety        : chr  "No" "Yes" "Yes" "No" ...
##  $ Stress.Level..1.10.              : int  10 1 1 4 1 9 8 5 2 5 ...
##  $ Heart.Rate..bpm.                 : int  114 62 91 86 98 84 118 113 81 95 ...
##  $ Breathing.Rate..breaths.min.     : int  14 23 28 17 19 14 21 19 22 28 ...
##  $ Sweating.Level..1.5.             : int  4 2 3 3 4 3 5 1 1 5 ...
##  $ Dizziness                        : chr  "No" "Yes" "No" "No" ...
##  $ Medication                       : chr  "Yes" "No" "No" "No" ...
##  $ Therapy.Sessions..per.month.     : int  3 2 1 0 1 2 1 0 2 1 ...
##  $ Recent.Major.Life.Event          : chr  "Yes" "No" "Yes" "No" ...
##  $ Diet.Quality..1.10.              : int  7 8 1 1 3 5 2 7 8 1 ...
##  $ Anxiety.Level..1.10.             : int  5 3 1 2 1 4 4 4 3 4 ...
\end{verbatim}

After Remove NAs, there are 1100 observations left.

\subsection{Data Splitting}\label{data-splitting}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2025}\NormalTok{)}
\NormalTok{train\_idx }\OtherTok{\textless{}{-}} \FunctionTok{createDataPartition}\NormalTok{(data1}\SpecialCharTok{$}\NormalTok{Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.}\NormalTok{, }\AttributeTok{p =} \FloatTok{0.75}\NormalTok{, }\AttributeTok{list =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{train\_data1 }\OtherTok{\textless{}{-}}\NormalTok{ data1[train\_idx, ]}
\NormalTok{test\_data1 }\OtherTok{\textless{}{-}}\NormalTok{ data1[}\SpecialCharTok{{-}}\NormalTok{train\_idx, ]}
\end{Highlighting}
\end{Shaded}

For Random Forest

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train\_data1\_rf }\OtherTok{\textless{}{-}}\NormalTok{ train\_data1}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Gender }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Gender)}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Occupation }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Occupation)}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Smoking }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Smoking)}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Family.History.of.Anxiety }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Family.History.of.Anxiety)}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Dizziness  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Dizziness)}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Medication  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Medication)}
\NormalTok{train\_data1\_rf}\SpecialCharTok{$}\NormalTok{Recent.Major.Life.Event }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(train\_data1}\SpecialCharTok{$}\NormalTok{Recent.Major.Life.Event )}

\NormalTok{test\_data1\_rf }\OtherTok{\textless{}{-}}\NormalTok{ test\_data1}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Gender }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Gender)}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Occupation }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Occupation)}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Smoking }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Smoking)}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Family.History.of.Anxiety }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Family.History.of.Anxiety)}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Dizziness  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Dizziness)}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Medication  }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Medication)}
\NormalTok{test\_data1\_rf}\SpecialCharTok{$}\NormalTok{Recent.Major.Life.Event }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(test\_data1}\SpecialCharTok{$}\NormalTok{Recent.Major.Life.Event )}
\end{Highlighting}
\end{Shaded}

For XgBoost

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Prepare data for XGBoost}
\NormalTok{X\_train }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.} \SpecialCharTok{\textasciitilde{}}\NormalTok{., }\AttributeTok{data =}\NormalTok{ train\_data1)}
\NormalTok{y\_train }\OtherTok{\textless{}{-}}\NormalTok{ train\_data1}\SpecialCharTok{$}\NormalTok{Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.}
\NormalTok{X\_test }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.} \SpecialCharTok{\textasciitilde{}}\NormalTok{., }\AttributeTok{data =}\NormalTok{ test\_data1)}
\NormalTok{y\_test }\OtherTok{\textless{}{-}}\NormalTok{ test\_data1}\SpecialCharTok{$}\NormalTok{Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.}
\end{Highlighting}
\end{Shaded}

\subsection{RandomForest}\label{randomforest}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2025}\NormalTok{)}

\CommentTok{\# 10{-}fold CV}
\NormalTok{control }\OtherTok{\textless{}{-}} \FunctionTok{trainControl}\NormalTok{(}
  \AttributeTok{method =} \StringTok{"cv"}\NormalTok{, }
  \AttributeTok{number =} \DecValTok{10}
\NormalTok{  )}

\CommentTok{\# train the rf using 10{-}fold CV}
\NormalTok{model }\OtherTok{\textless{}{-}}\NormalTok{ caret}\SpecialCharTok{::}\FunctionTok{train}\NormalTok{(}
\NormalTok{  Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.} \SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }
  \AttributeTok{data =}\NormalTok{ train\_data1\_rf, }
  \AttributeTok{method =} \StringTok{"rf"}\NormalTok{, }
  \AttributeTok{trControl =}\NormalTok{ control}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

BestTune

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model}\SpecialCharTok{$}\NormalTok{bestTune}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   mtry
## 2   16
\end{verbatim}

Variable Importance as barplot

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final\_model }\OtherTok{\textless{}{-}}\NormalTok{ model}\SpecialCharTok{$}\NormalTok{finalModel}
\FunctionTok{barplot}\NormalTok{(randomForest}\SpecialCharTok{::}\FunctionTok{importance}\NormalTok{(final\_model)[,}\StringTok{"IncNodePurity"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\includegraphics{AMS-580-Final-Exam_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2025}\NormalTok{)}
\NormalTok{rf }\OtherTok{\textless{}{-}} \FunctionTok{randomForest}\NormalTok{(}
\NormalTok{  Anxiety.Level..}\DecValTok{1}\NormalTok{.}\FloatTok{10.}\SpecialCharTok{\textasciitilde{}}\NormalTok{.,}
  \AttributeTok{data=}\NormalTok{train\_data1\_rf,}
  \AttributeTok{mtry=}\DecValTok{16}\NormalTok{,}
  \AttributeTok{keep.forest=}\ConstantTok{FALSE}\NormalTok{, }\CommentTok{\#not save each individual CART tree in the output}
  \AttributeTok{importance=}\ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{RMSE}\label{rmse}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sqrt}\NormalTok{(rf}\SpecialCharTok{$}\NormalTok{mse[}\DecValTok{500}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.104186
\end{verbatim}

\subsection{XgBoost}\label{xgboost}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dtrain }\OtherTok{\textless{}{-}} \FunctionTok{xgb.DMatrix}\NormalTok{(}\AttributeTok{data =}\NormalTok{ X\_train, }\AttributeTok{label =}\NormalTok{ y\_train)}
\NormalTok{dtest }\OtherTok{\textless{}{-}} \FunctionTok{xgb.DMatrix}\NormalTok{(}\AttributeTok{data =}\NormalTok{ X\_test, }\AttributeTok{label =}\NormalTok{ y\_test)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train XGBoost}
\NormalTok{xgb\_model }\OtherTok{\textless{}{-}} \FunctionTok{xgboost}\NormalTok{(}
  \AttributeTok{data =}\NormalTok{ dtrain,}
  \AttributeTok{nrounds =} \DecValTok{500}\NormalTok{,}
  \AttributeTok{eta =} \FloatTok{0.1}\NormalTok{,}
  \AttributeTok{verbose =} \DecValTok{0}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Feature importance plot}
\NormalTok{importance }\OtherTok{\textless{}{-}} \FunctionTok{xgb.importance}\NormalTok{(}\AttributeTok{feature\_names =} \FunctionTok{colnames}\NormalTok{(X\_train), }\AttributeTok{model =}\NormalTok{ xgb\_model)}
\FunctionTok{xgb.plot.importance}\NormalTok{(importance, }\AttributeTok{main =} \StringTok{"XGBoost Feature Importance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{AMS-580-Final-Exam_files/figure-latex/unnamed-chunk-15-1.pdf}

Prediction

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xgb\_preds }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(xgb\_model, X\_test)}
\end{Highlighting}
\end{Shaded}

RMSE

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((y\_test }\SpecialCharTok{{-}}\NormalTok{ xgb\_preds)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.165522
\end{verbatim}

\subsection{Comparison}\label{comparison}

Model Test MSE

\begin{itemize}
\item
  RF: 1.104186
\item
  XGB: 1.165522
\end{itemize}

The reason why RF outperform XGB

\begin{itemize}
\item
  Number of Features- since XGB used one-hot-encoding so there is a risk
  of multicolinearity problem which overfit the training data
\item
  Cross-Validation: since we used cross validation to find the optimal
  mtry for rf and in XGB, we didn't use CV to tune hyper-parameter. It
  can result in RF performs better than XGB
\end{itemize}

\section{Task 2}\label{task-2}

\subsection{Import Data}\label{import-data-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data2 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"/Users/thomashuang/Downloads/data\_2.csv"}\NormalTok{)}
\NormalTok{data2}\SpecialCharTok{$}\NormalTok{Date }\OtherTok{=} \FunctionTok{as.Date}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{Date)}
\FunctionTok{head}\NormalTok{(data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Date AMZN.Open AMZN.High AMZN.Low AMZN.Close AMZN.Volume AMZN.Adjusted
## 1 2023-01-03     85.46     86.96    84.21      85.82    76706000         85.82
## 2 2023-01-04     86.55     86.98    83.36      85.14    68885100         85.14
## 3 2023-01-05     85.33     85.42    83.07      83.12    67930800         83.12
## 4 2023-01-06     83.03     86.40    81.43      86.08    83303400         86.08
## 5 2023-01-09     87.46     89.48    87.08      87.36    65266100         87.36
## 6 2023-01-10     87.57     90.19    87.29      89.87    67756600         89.87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    590 obs. of  7 variables:
##  $ Date         : Date, format: "2023-01-03" "2023-01-04" ...
##  $ AMZN.Open    : num  85.5 86.6 85.3 83 87.5 ...
##  $ AMZN.High    : num  87 87 85.4 86.4 89.5 ...
##  $ AMZN.Low     : num  84.2 83.4 83.1 81.4 87.1 ...
##  $ AMZN.Close   : num  85.8 85.1 83.1 86.1 87.4 ...
##  $ AMZN.Volume  : int  76706000 68885100 67930800 83303400 65266100 67756600 103126200 85254800 85549400 72755000 ...
##  $ AMZN.Adjusted: num  85.8 85.1 83.1 86.1 87.4 ...
\end{verbatim}

\subsection{1. Data preprocessing and
visualization}\label{data-preprocessing-and-visualization}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}
\NormalTok{  data2, }
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Date, }\AttributeTok{y =}\NormalTok{ AMZN.Close)}
\NormalTok{) }\SpecialCharTok{+} \FunctionTok{geom\_line}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{AMS-580-Final-Exam_files/figure-latex/unnamed-chunk-20-1.pdf}

normalization

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data2}\SpecialCharTok{$}\NormalTok{min\_lagged }\OtherTok{=} \FunctionTok{lag}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{AMZN.Low)}
\NormalTok{data2}\SpecialCharTok{$}\NormalTok{max\_lagged }\OtherTok{=} \FunctionTok{lag}\NormalTok{(data2}\SpecialCharTok{$}\NormalTok{AMZN.High)}

\NormalTok{data2}\SpecialCharTok{$}\NormalTok{Close\_norm }\OtherTok{=}\NormalTok{ (data2}\SpecialCharTok{$}\NormalTok{AMZN.Close }\SpecialCharTok{{-}}\NormalTok{ data2}\SpecialCharTok{$}\NormalTok{min\_lagged) }\SpecialCharTok{/}\NormalTok{ (data2}\SpecialCharTok{$}\NormalTok{max\_lagged }\SpecialCharTok{{-}}\NormalTok{data2}\SpecialCharTok{$}\NormalTok{min\_lagged)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_data }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}
\NormalTok{  data2}\SpecialCharTok{$}\NormalTok{Close\_norm[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{] }\CommentTok{\#excluding volume}
\NormalTok{)}
\FunctionTok{tail}\NormalTok{(model\_data,}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                [,1]
## [580,]  0.496627634
## [581,]  0.469042991
## [582,]  0.170507723
## [583,]  1.830644586
## [584,]  0.575405367
## [585,] -0.007714153
## [586,] -0.196228479
## [587,]  1.191180540
## [588,]  1.182273300
## [589,]  0.769508977
\end{verbatim}

\subsection{2. Data Splitting}\label{data-splitting-1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2025}\NormalTok{)}

\CommentTok{\# Create sliding window dataset}
\NormalTok{create\_dataset }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(series, }\AttributeTok{timesteps =} \DecValTok{10}\NormalTok{) \{}
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}
\NormalTok{  y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{()}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(series) }\SpecialCharTok{{-}}\NormalTok{ timesteps)) \{}
\NormalTok{  x[[i]] }\OtherTok{\textless{}{-}}\NormalTok{ series[i}\SpecialCharTok{:}\NormalTok{(i }\SpecialCharTok{+}\NormalTok{ timesteps }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)]}
\NormalTok{  y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(y, series[i }\SpecialCharTok{+}\NormalTok{ timesteps])}
\NormalTok{  \}}
\NormalTok{  x\_array }\OtherTok{\textless{}{-}} \FunctionTok{do.call}\NormalTok{(rbind, x)}
  \FunctionTok{return}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x\_array, }\AttributeTok{y =}\NormalTok{ y))}
\NormalTok{\}}

\CommentTok{\# Prepare training data}
\NormalTok{timesteps }\OtherTok{\textless{}{-}} \DecValTok{10}

\NormalTok{train\_data2 }\OtherTok{\textless{}{-}}\NormalTok{ model\_data[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(model\_data)}\SpecialCharTok{{-}}\DecValTok{10}\NormalTok{)] }\CommentTok{\# training = all except last 10 days}

\NormalTok{test\_data2 }\OtherTok{\textless{}{-}}\NormalTok{ model\_data[(}\FunctionTok{length}\NormalTok{(model\_data)}\SpecialCharTok{{-}}\DecValTok{9}\NormalTok{)}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(model\_data)] }\CommentTok{\# true last 10 points}

\NormalTok{train\_set2 }\OtherTok{\textless{}{-}} \FunctionTok{create\_dataset}\NormalTok{(train\_data2, timesteps)}

\NormalTok{x\_train\_array }\OtherTok{\textless{}{-}} \FunctionTok{array}\NormalTok{(}
  \FunctionTok{as.numeric}\NormalTok{(train\_set2}\SpecialCharTok{$}\NormalTok{x), }
  \AttributeTok{dim =} \FunctionTok{c}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(train\_set2}\SpecialCharTok{$}\NormalTok{x), timesteps, }\DecValTok{1}\NormalTok{)}
\NormalTok{)}

\NormalTok{y\_train\_array }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(train\_set2}\SpecialCharTok{$}\NormalTok{y)}

\NormalTok{x\_train2 }\OtherTok{\textless{}{-}}\NormalTok{ tf}\SpecialCharTok{$}\FunctionTok{convert\_to\_tensor}\NormalTok{(}
\NormalTok{  x\_train\_array, }
  \AttributeTok{dtype =} \StringTok{"float32"}
\NormalTok{)}

\NormalTok{y\_train2 }\OtherTok{\textless{}{-}}\NormalTok{ tf}\SpecialCharTok{$}\FunctionTok{convert\_to\_tensor}\NormalTok{(}
\NormalTok{  y\_train\_array, }
  \AttributeTok{dtype =} \StringTok{"float32"}
\NormalTok{)}

\FunctionTok{dim}\NormalTok{(x\_train2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 569  10   1
\end{verbatim}

The dimension of the training data is 569(rows) and 10(columns)

\subsection{LSTM}\label{lstm}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{input\_lstm }\OtherTok{\textless{}{-}} \FunctionTok{layer\_input}\NormalTok{(}\AttributeTok{shape =} \FunctionTok{c}\NormalTok{(timesteps, }\DecValTok{1}\NormalTok{))}

\NormalTok{output\_lstm }\OtherTok{\textless{}{-}}\NormalTok{ input\_lstm }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{layer\_lstm}\NormalTok{(}\AttributeTok{units =} \DecValTok{32}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{layer\_dense}\NormalTok{(}\AttributeTok{units =} \DecValTok{1}\NormalTok{)}

\NormalTok{model\_lstm }\OtherTok{\textless{}{-}} \FunctionTok{keras\_model}\NormalTok{(}\AttributeTok{inputs =}\NormalTok{ input\_lstm, }\AttributeTok{outputs =}\NormalTok{ output\_lstm)}

\NormalTok{model\_lstm}\SpecialCharTok{$}\FunctionTok{compile}\NormalTok{(}
  \AttributeTok{loss =} \StringTok{"mean\_squared\_error"}
\NormalTok{)}

\NormalTok{history\_lstm }\OtherTok{\textless{}{-}}\NormalTok{ model\_lstm}\SpecialCharTok{$}\FunctionTok{fit}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ x\_train2,}
  \AttributeTok{y =}\NormalTok{ y\_train2,}
  \AttributeTok{epochs =} \FunctionTok{r\_to\_py}\NormalTok{(}\DecValTok{100}\DataTypeTok{L}\NormalTok{),}
  \AttributeTok{batch\_size =} \FunctionTok{r\_to\_py}\NormalTok{(}\DecValTok{16}\DataTypeTok{L}\NormalTok{),}
  \AttributeTok{verbose =} \DecValTok{0}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{RNN}\label{rnn}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{input\_rnn }\OtherTok{\textless{}{-}} \FunctionTok{layer\_input}\NormalTok{(}\AttributeTok{shape =} \FunctionTok{c}\NormalTok{(timesteps, }\DecValTok{1}\NormalTok{))}

\NormalTok{output\_rnn }\OtherTok{\textless{}{-}}\NormalTok{ input\_rnn }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{layer\_simple\_rnn}\NormalTok{(}\AttributeTok{units =} \DecValTok{32}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{layer\_dense}\NormalTok{(}\AttributeTok{units =} \DecValTok{1}\NormalTok{)}

\NormalTok{model\_rnn }\OtherTok{\textless{}{-}} \FunctionTok{keras\_model}\NormalTok{(}\AttributeTok{inputs =}\NormalTok{ input\_rnn, }\AttributeTok{outputs =}\NormalTok{ output\_rnn)}

\NormalTok{model\_rnn}\SpecialCharTok{$}\FunctionTok{compile}\NormalTok{(}
  \AttributeTok{loss =} \StringTok{"mean\_squared\_error"}
\NormalTok{)}

\NormalTok{history\_rnn }\OtherTok{\textless{}{-}}\NormalTok{ model\_rnn}\SpecialCharTok{$}\FunctionTok{fit}\NormalTok{(}
  \AttributeTok{x =}\NormalTok{ x\_train2,}
  \AttributeTok{y =}\NormalTok{ y\_train2,}
  \AttributeTok{epochs =} \FunctionTok{r\_to\_py}\NormalTok{(}\DecValTok{100}\DataTypeTok{L}\NormalTok{),}
  \AttributeTok{batch\_size =} \FunctionTok{r\_to\_py}\NormalTok{(}\DecValTok{16}\DataTypeTok{L}\NormalTok{),}
  \AttributeTok{verbose =} \DecValTok{0}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Prepare input for forecasting}
\NormalTok{input\_seq }\OtherTok{\textless{}{-}}\NormalTok{ model\_data[(}\FunctionTok{length}\NormalTok{(model\_data)}\SpecialCharTok{{-}}\DecValTok{10}\NormalTok{)}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(model\_data)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)] }\CommentTok{\# 10 points before test}

\NormalTok{input\_seq\_array }\OtherTok{\textless{}{-}} \FunctionTok{array}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(input\_seq), }\AttributeTok{dim =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, timesteps,}\DecValTok{1}\NormalTok{))}

\NormalTok{input\_seq\_array }\OtherTok{\textless{}{-}}\NormalTok{ tf}\SpecialCharTok{$}\FunctionTok{convert\_to\_tensor}\NormalTok{(input\_seq\_array, }\AttributeTok{dtype =} \StringTok{"float32"}\NormalTok{)}

\CommentTok{\# Prediction function}
\NormalTok{predict\_next }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(model, input\_seq\_array, }\AttributeTok{n\_steps =} \DecValTok{10}\NormalTok{) \{}
\NormalTok{  preds }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{()}
\NormalTok{  current\_input }\OtherTok{\textless{}{-}}\NormalTok{ input\_seq\_array}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_steps) \{}
\NormalTok{    pred }\OtherTok{\textless{}{-}}\NormalTok{ model}\SpecialCharTok{$}\FunctionTok{predict}\NormalTok{(current\_input)}
\NormalTok{    preds }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(preds, }\FunctionTok{as.numeric}\NormalTok{(pred))}
\NormalTok{    updated\_seq }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(current\_input)[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{], }\FunctionTok{as.numeric}\NormalTok{(pred))}
\NormalTok{    current\_input }\OtherTok{\textless{}{-}} \FunctionTok{array}\NormalTok{(updated\_seq, }\AttributeTok{dim =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, timesteps, }\DecValTok{1}\NormalTok{))}
\NormalTok{    current\_input }\OtherTok{\textless{}{-}}\NormalTok{ tf}\SpecialCharTok{$}\FunctionTok{convert\_to\_tensor}\NormalTok{(current\_input, }\AttributeTok{dtype =} \StringTok{"float32"}\NormalTok{)}
\NormalTok{  \}}
  \FunctionTok{return}\NormalTok{(preds)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lstm\_preds\_norm }\OtherTok{\textless{}{-}} \FunctionTok{predict\_next}\NormalTok{(}
\NormalTok{  model\_lstm, }
\NormalTok{  input\_seq\_array, }
  \AttributeTok{n\_steps =} \DecValTok{10}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 51ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 57ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 6ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rnn\_preds\_norm }\OtherTok{\textless{}{-}} \FunctionTok{predict\_next}\NormalTok{(}
\NormalTok{  model\_rnn, }
\NormalTok{  input\_seq\_array, }
  \AttributeTok{n\_steps =} \DecValTok{10}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 42ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 49ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 6ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 6ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 7ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 13ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 6ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
## [1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 6ms/step[1m1/1[0m [32m━━━━━━━━━━━━━━━━━━━━[0m[37m[0m [1m0s[0m 12ms/step
\end{verbatim}

Scale Back

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Initialize vectors to store scaled{-}back predictions and true prices}
\NormalTok{lstm\_preds\_original }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\NormalTok{true\_prices\_original }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\NormalTok{rnn\_preds\_original }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(}\DecValTok{10}\NormalTok{)}

\CommentTok{\# Scale back one by one (because each day uses its own lagged High/Low)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{) \{}
\NormalTok{  lagged\_min }\OtherTok{\textless{}{-}}\NormalTok{ data2}\SpecialCharTok{$}\NormalTok{AMZN.Low[}\FunctionTok{length}\NormalTok{(train\_data2) }\SpecialCharTok{+}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{] }\CommentTok{\# lag(Low) for that day}
\NormalTok{  lagged\_max }\OtherTok{\textless{}{-}}\NormalTok{ data2}\SpecialCharTok{$}\NormalTok{AMZN.High[}\FunctionTok{length}\NormalTok{(train\_data2) }\SpecialCharTok{+}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{] }\CommentTok{\# lag(High) for that day}
\NormalTok{  rnn\_preds\_original[i] }\OtherTok{\textless{}{-}}\NormalTok{ rnn\_preds\_norm[i] }\SpecialCharTok{*}\NormalTok{ (lagged\_max }\SpecialCharTok{{-}}\NormalTok{ lagged\_min) }\SpecialCharTok{+}\NormalTok{ lagged\_min}
\NormalTok{  lstm\_preds\_original[i] }\OtherTok{\textless{}{-}}\NormalTok{ lstm\_preds\_norm[i] }\SpecialCharTok{*}\NormalTok{ (lagged\_max }\SpecialCharTok{{-}}\NormalTok{ lagged\_min) }\SpecialCharTok{+}\NormalTok{ lagged\_min}
\NormalTok{  true\_prices\_original[i] }\OtherTok{\textless{}{-}}\NormalTok{ data2}\SpecialCharTok{$}\NormalTok{AMZN.Close[}\FunctionTok{length}\NormalTok{(train\_data2) }\SpecialCharTok{+}\NormalTok{ i] }\CommentTok{\# true Close at day}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

MSE

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse\_rnn }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((rnn\_preds\_original }\SpecialCharTok{{-}}\NormalTok{ true\_prices\_original)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\NormalTok{mse\_lstm }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((lstm\_preds\_original }\SpecialCharTok{{-}}\NormalTok{ true\_prices\_original)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Test MSE (RNN, original scale):"}\NormalTok{, mse\_rnn, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Test MSE (RNN, original scale): 17.36946
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Test MSE (LSTM, original scale):"}\NormalTok{, mse\_lstm, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Test MSE (LSTM, original scale): 13.63753
\end{verbatim}

Plot 10-Day Forecast (Original Scale)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  (}\FunctionTok{length}\NormalTok{(train\_data2)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(train\_data2)}\SpecialCharTok{+}\DecValTok{10}\NormalTok{),}
\NormalTok{  true\_prices\_original,}
  \AttributeTok{type =} \StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }
  \AttributeTok{lwd =} \DecValTok{2}\NormalTok{, }
  \AttributeTok{col =} \StringTok{\textquotesingle{}black\textquotesingle{}}\NormalTok{, }
  \AttributeTok{xlab =} \StringTok{"Time Index"}\NormalTok{, }
  \AttributeTok{ylab =} \StringTok{"Close Price (USD)"}\NormalTok{,}
  \AttributeTok{main =} \StringTok{"10{-}Day Forecast vs True (Original Scale)"}
\NormalTok{)}

\FunctionTok{lines}\NormalTok{(}
\NormalTok{  (}\FunctionTok{length}\NormalTok{(train\_data2)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(train\_data2)}\SpecialCharTok{+}\DecValTok{10}\NormalTok{),}
\NormalTok{  rnn\_preds\_original, }
  \AttributeTok{col =} \StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{, }
  \AttributeTok{lwd =} \DecValTok{2}
\NormalTok{)}

\FunctionTok{lines}\NormalTok{(}
\NormalTok{  (}\FunctionTok{length}\NormalTok{(train\_data2)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(train\_data2)}\SpecialCharTok{+}\DecValTok{10}\NormalTok{),}
\NormalTok{  lstm\_preds\_original, }
  \AttributeTok{col =} \StringTok{\textquotesingle{}blue\textquotesingle{}}\NormalTok{, }
  \AttributeTok{lwd =} \DecValTok{2}
\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}
  \StringTok{"bottomleft"}\NormalTok{, }
  \AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"True Close"}\NormalTok{, }\StringTok{"RNN Prediction"}\NormalTok{, }\StringTok{"LSTM Prediction"}\NormalTok{),}
  \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{), }
  \AttributeTok{lwd =} \DecValTok{2}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{AMS-580-Final-Exam_files/figure-latex/unnamed-chunk-31-1.pdf}

\subsection{Comparison}\label{comparison-1}

Model Test MSE (Original USD Scale)

\begin{itemize}
\item
  RNN: 16.05965
\item
  LSTM: 14.42587
\item
  LSTM has lower MSE than RNN. LSTM outperforms RNN when predicting
  actual stock prices.
\end{itemize}

The reason why LSTM outperform RNN

\begin{itemize}
\item
  The algorithm difference between LSTM and RNN. LSTM is known to be
  improvement over RNN because LSTM has separate memory cells and three
  gates.
\item
  Vanish/Exploding Gradient Problem, one biggest issue that RNN has

  \begin{itemize}
  \tightlist
  \item
    When we train RNN, Gradient can vanish or it can explode, either one
    would result in bad prediction
  \end{itemize}
\end{itemize}

\end{document}
